.TH "FEEDAGREGATOR" "1" "March 2019" "feedagregator 1.3.0" ""
.SH NAME
FeedAgregator \- RSS and Atom feed agregator in desktop widgets + notifications
.SH SYNOPSIS
.B feedagregator
.SH DESCRIPTION
FeedAgregator periodically looks for RSS/Atom feed updates. 
If an update is found, a notification is sent. In addition, a desktop 
widget show the latest entry of all feeds and for each feed, a widget
shows all entries.
.SH AUTHOR
FeedAgregator is developped by Juliette Monsel <j_4321@protonmail.com>
.SH BUGS
Please submit bugs on the Github page of the project
\fBhttps://github.com/j4321/FeedAgregator/issues\fR 
or send an email to <j_4321@protonmail.com>.
